project:
  type: book
  execute-dir: project
  output-dir: docs

book:
  title: "R for reproducible spatial analysis"
  subtitle: "IP: Application Development (GIS) - Part 2"
  author:
    - name: Lorena Abad
      email: lorena.abad@plus.ac.at
      orcid: 0000-0003-0554-734X
  date: "today"
  chapters:
    - index.qmd
    - part: "Lessons"
      chapters:
        - lessons/placeholder.qmd
    - part: "Practicals"
      chapters: 
        # - practicals/Practical1/Practical1-Getting-Started-R.qmd
        # - practicals/Practical2/Practical2-Base-R.qmd
        # - practicals/Practical3/Practical3-Writing-Functions.qmd
        # - practicals/Practical4/Practical4.qmd
        # - practicals/Practical5/Practical5-Spatial-Data-Analysis.qmd
        # - practicals/Practical6/Practical6.qmd
        - misc/x_error-handling.qmd
    # - project/final-project.qmd
  repo-url: "https://github.com/loreabad6/app-dev-gis"
  page-footer:
    center: "Department of Geoinformatics — Z_GIS, University of Salzburg"
    left: "Winter Semester 2024/2025"
    right:
      - text: "CC-BY-4.0"
        href: License.md
  sidebar:
    search: true
format:
  html:
    number-sections: true
    css: html-styling/style.css
    theme:
      light: cosmo
      dark: [cosmo, html-styling/theme-dark.scss]
# bibliography: 
#     - packages-index.bib
#     - packages-vector.bib
#     - packages-raster.bib
#     - "https://api.citedrive.com/bib/f67c224b-6fcd-4870-87fc-67374abf013e/references.bib?x=eyJpZCI6ICJmNjdjMjI0Yi02ZmNkLTQ4NzAtODdmYy02NzM3NGFiZjAxM2UiLCAidXNlciI6ICIyNTY4IiwgInNpZ25hdHVyZSI6ICJiZmJhYzUyOThkY2E0ZWI4MjZjNjVkMDQ5MDc2N2I0OGVmMjQ1ZmI4ODMwYmVhYjllYmIwNmJiMTY0MWVlYThmIn0=/bibliography.bib"
# 
# nocite: |
#   @*
knitr:
  opts_chunk:
    classes: styled-output
    fig-crop: true
    tidy.opts: { width.cutoff: 80 }
    # dev.args:
      # bg: transparent