project:
  type: book
  execute-dir: project
  output-dir: docs

book:
  title: "R for reproducible spatial analysis"
  subtitle: "IP: Application Development (GIS) - Part 1"
  author:
    - name: Lorena Abad
      email: lorena.abad@plus.ac.at
      orcid: 0000-0003-0554-734X
  date: "today"
  chapters:
    - index.qmd
    - part: "Lessons"
      chapters:
        # - lessons/placeholder.qmd
        - lessons/session_1.qmd
        - lessons/session_2.qmd
        - lessons/session_3.qmd
        - lessons/session_4.qmd
        # - lessons/session_5.qmd
        # - lessons/session_6.qmd
        # - lessons/session_7.qmd
    - part: "Practicals"
      chapters: 
        # - lessons/placeholder.qmd
        - practicals/Practical1/preparation/Practical1-Base-R-Functions.qmd
        - practicals/Practical2/Practical2-DataViz.qmd
        - practicals/Practical3/preparation/Practical3-Spatial-Data-Analysis.qmd
        # - practicals/Practical4/preparation/Practical4-R-package.qmd
    - part: "Annex"
      chapters: 
        - misc/x_error-handling.qmd
        - misc/x_ask_help.qmd
    # - final-project.qmd
    - refs/references.qmd
  repo-url: "https://github.com/loreabad6/app-dev-gis"
  page-footer:
    center: "Department of Geoinformatics — Z_GIS, University of Salzburg"
    left: "Summer Semester 2025"
    right:
      - text: "CC-BY-4.0"
        href: License.md
  sidebar:
    search: true
format:
  html:
    number-sections: true
    css: html-styling/style.css
    theme:
      light: cosmo
      dark: [cosmo, html-styling/theme-dark.scss]
bibliography:
    - "https://api.citedrive.com/bib/9599d778-9673-485f-93bd-bad1a2f62dd4/references.bib?x=eyJpZCI6ICI5NTk5ZDc3OC05NjczLTQ4NWYtOTNiZC1iYWQxYTJmNjJkZDQiLCAidXNlciI6ICIyNTY4IiwgInNpZ25hdHVyZSI6ICI2N2I0ZTc3NTYxOTBhYzc1NTIxMzViNGQ0ODM3NmNmNTEyY2Y1ZjgzYTlkMzgzYmM3ZTc3MDI0ZTA0OTk2NGVhIn0=/bibliography.bib"
    - refs/packages-index.bib
    - refs/packages-tidyr.bib
    - refs/packages-rspatial.bib
    - refs/packages-rbridges.bib
    - refs/packages-rpkgs.bib
nocite: |
  @*
csl: https://raw.githubusercontent.com/citation-style-language/styles/refs/heads/master/apa.csl
prefer-html: true
knitr:
  opts_chunk:
    classes: styled-output
    fig-crop: true
    tidy.opts: { width.cutoff: 80 }
    # dev.args:
      # bg: transparent