# Syllabus {.unnumbered}

::: smaller
|  |  |
|-----------------|-------------------------------------------------------|
| Time | From 07.03.25 - Fridays 12:00-14:30 |
| Location | [GI_Lab](https://online.uni-salzburg.at/plus_online/ee/ui/ca2/app/desktop/#/pl/ui/$ctx/ris.ris?$ctx=design=ca2;header=max;lang=EN&corg=19091&pActionFlag=A&pQuellGeogrBTypNr=5&pRaumNr=35443&pShowEinzelraum=J&pZielGeogrBTypNr=5&pZielGeogrBerNr=5830001), 1st Floor, Building 15, Techno_Z, Schillerstr. 30, 5020 Salzburg |
| Expected effort | Both parts: 6 ECTS (i.e. 150 hours), 3 semester hour per week in class |
| Office hours | via Blackboard or [by appointment](https://outlook.office.com/bookwithme/user/5edd6ea20ab443ed98d843c0da618b2f%40plus.ac.at?anonymous&isanonymous=true) |
:::

{{< include README.md >}}

## Schedule and format

This is the tentative course schedule of the lessons and assignments.

::: smaller
| DATE | TOPIC | ACTIVITY | DUE DATE |
|:-------------:|-----------------------------|---------------|---------------|
| 07.03.25 | Intro to R, RStudio, Quarto; how to ask for help? |  |  |
| 14.03.25 | Fundamentals of R; functional programming | Practical 1 | End of class |
| 21.03.25 | (Spatial) data cleaning, wrangling & plotting | Hands-on;<br>Practical 2[^*] | <br>05.05.25 |
| 28.03.25 | R-spatial ecosystem, vector, raster, data cubes | Practical 3 | End of class |
| 04.04.25 | GIS: in-house and bridges | Hands-on |  |
| 11.04.25 | Quarto interactive dashboards | |  |
| 09.05.25 | R package development | Practical 2 showcase | |
:::

[^*]: Explanation of assignment

The lessons are meant to give you a broad overview of the basics and of what is possible with R for spatial analysis. ***Learning by yourself is highly encouraged and expected!***

The @sec-compmaterials section lists a number of additional resources for your self-learning, and at the end of the lessons you will have references to the relevant chapters for you to go through.

In class, we will work with hand-on practicals that will allow you to develop R skills from the first lesson.

If you find yourself taking longer or having trouble with concepts, please ask for help on the course’s Blackboard message board or in class (there is an excellent chance someone else has the same question!) rather than via e-mail.

{{< include misc/x_genAI.qmd >}}

## Assignments and grading

-   Practical exercises (3) – 30%
    -   To be submitted by the end of the class or by a specific date
-   End-of-term assignment – 50%
    -   Programming project, either R or Python or both
-   Active participation – 20%

## Required course materials

R, RStudio, and Rtools will be installed in the lab computers. If you use your own laptop, see the @sec-compmaterials section below.

## Complementary course materials {#sec-compmaterials}

### Install R and Co.

To work on your own laptop, you need to install R, RStudio and Quarto to follow the course materials.

-   Install R (\>= 4.0) and RStudio (\>= 2024.04.x with Quarto). You can follow the steps in Appendix 1 of [Hands-On Programming with R](https://rstudio-education.github.io/hopr/starting.html).
-   If you are on Windows, install [Rtools for the R version](https://cran.r-project.org/bin/windows/Rtools/) you have.
-   Installing R spatial packages in Windows (Rtools is required, see above) and Mac should be straightforward, and we will do it together. If you have a Linux system, please read [this blogpost](https://geocompx.org/post/2020/installing-r-spatial-packages-linux/index.html).

If you have any problems with installation, please reach out via Blackboard.

### R programming resources

#### Intro & Basics

-   [RYouWithMe](https://rladiessydney.org/courses/ryouwithme/) from R-Ladies Sydney.
-   [fasteR: Fast Lane to Learning R!](https://github.com/matloff/fasteR) by Norm Matloff.
-   [Teacups, Giraffes, & Statistics](https://tinystats.github.io/teacups-giraffes-and-statistics/index.html) by Hasse Walum and Desiree de Leon.

##### Interactive R learning

-   Learn or freshen up R basics interactively with [swirl](https://swirlstats.com/students.html)
    -   Follow the instructions to start interactive courses from the R console.
    -   Check Step 5 for instructions to download more courses, in different languages available at the [Swirl Course Network](https://swirlstats.com/scn/title.html).

#### Books

##### Entry-level

-   [Hands-on programming with R](https://rstudio-education.github.io/hopr/) by Garrett Grolemund.
-   [R for Data Science (2e)](https://r4ds.hadley.nz/) by Hadley Wickham, Mine Çetinkaya-Rundel and Garrett Grolemund.

##### R-Spatial

-   [Geocomputation with R](https://r.geocompx.org/) by Robin Lovelace, Jakub Nowosad and Jannes Muenchow.
-   [Spatial Data Science: With Applications in R](https://r-spatial.org/book/) by Edzer Pebesma and Roger Bivand.
-   [Spatial Data Science with R and “terra”](https://rspatial.org/) by Robert Hijmans.

##### Advanced

-   [Advanced R (2e)](https://adv-r.hadley.nz/) by Hadley Wickham
-   [R Packages (2e)](https://r-pkgs.org/) by Hadley Wickham and Jennifer Bryan

All links to these materials are also included in Blackboard.

::: callout-note
### Disclaimer

Please note that the specifics of this Course Syllabus can be changed at any time, and you will be responsible for abiding by any such changes. Any changes will be communicated in class, via e-mail, or course announcement via Blackboard.
:::

```{r}
#| include: false
# automatically create a bib database for R packages
knitr::write_bib(c('knitr', 'quarto'), 'refs/packages-index.bib')
```
