on:
  workflow_dispatch:
  push:
    branches: main
    tags: ['*']

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      # - name: Publish to GitHub Pages
      #   uses: quarto-dev/quarto-actions/publish@v2
      #   with:
      #     target: gh-pages
      #     path: docs
      #     render: false
      - name: Publish Quarto Book
        run: quarto publish gh-pages --no-input
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}