name: Publish

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Ensure all history is fetched

    - name: Deploy to GitHub Pages
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git checkout --orphan "${GITHUB_REF##*/}"
        git reset
        git add docs/
        git commit -m "Deploy site for ${GITHUB_REF##*/}"
        git push origin "${GITHUB_REF##*/}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}